// Generated by Wrangler by running `wrangler types`
// Extended for Google OAuth + D1 Authentication

/// <reference types="@cloudflare/workers-types" />

// Extend the global CloudflareEnv interface used by @cloudflare/next-on-pages
declare global {
	interface CloudflareEnv {
		// OpenAI
		OPENAI_API_KEY: string;

		// Google OAuth
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;

		// Session
		SESSION_SECRET: string;

		// KV Namespaces
		USER_LOGIN: KVNamespace;
		KV_STORE: KVNamespace;

		// D1 Database
		DB: D1Database;
	}
}

// Also export as Env for backward compatibility
interface Env extends CloudflareEnv {}

export {};
